config/routes.rb
Rails.application.routes.draw do

	# routes for omniauth log in
	get '/auth/:provider/callback', to: 'sessions#create'
	get '/auth/failure', to: redirect('/')

	# route for log out
	get '/logout', to: 'sessions#destroy', as: :logout

	# routes for creating new tweets
	resources :tweets, only: [:new, :create]

	# route for homepage
	root to: 'site#index'

end

app/models/user.rb
class User < ActiveRecord::Base

  # uses omniauth to check Twitter and log in to app
  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid).permit!).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.oauth_secret = auth.credentials.secret
      user.save!
    end
  end

  # uses omniauth to create tweets and send them to Twitter
  def tweet(tweet)
    client = Twitter::REST::Client.new do |config|
      config.consumer_key        = Rails.application.config.twitter_key
      config.consumer_secret     = Rails.application.config.twitter_secret
      config.access_token        = oauth_token
      config.access_token_secret = oauth_secret
    end
    client.update(tweet)
  end

  # grabs Twitter user's home_timeline
  def home_timeline
    client = Twitter::REST::Client.new do |config|
      config.consumer_key        = Rails.application.config.twitter_key
      config.consumer_secret     = Rails.application.config.twitter_secret
      config.access_token        = oauth_token
      config.access_token_secret = oauth_secret
    end
    return client.home_timeline
  end

  # grabs Twitter user's user_timeline
  def user_timeline
    client = Twitter::REST::Client.new do |config|
      config.consumer_key        = Rails.application.config.twitter_key
      config.consumer_secret     = Rails.application.config.twitter_secret
      config.access_token        = oauth_token
      config.access_token_secret = oauth_secret
    end
    return client.user_timeline
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # @current_user is either the current user, or nil
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  # can use current_user in all the views
  helper_method :current_user

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  # creations session based on the omniauth data
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    flash[:notice] = "Successfully logged in"
    redirect_to root_path
  end

  # log out / destroys the session
  def destroy
    session[:user_id] = nil
    flash[:error] = "Successfully logged out"
    redirect_to root_path
  end

end

app/controllers/site_controller.rb
class SiteController < ApplicationController

  def index
  end

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

  def new
  end
	
  # creates a new tweet based on the twitter parameters
  def create
    # makes sure user is logged in
    if current_user
      if current_user.tweet(twitter_params[:message])
        flash[:notice] = "Successfully tweeted!"
        redirect_to root_path
      else
        # server-side error handling
        flash[:error] = tweet.errors.full_messages.join(', ')
        redirect_to root_path
      end
    else
      flash[:error] = "Need to log in to create tweet"
      redirect_to root_path
    end
  end

  # sets the parameters for tweets
  def twitter_params
    params.require(:tweet).permit(:message)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/_navbar.html.erb
<header>
	<nav class="navbar navbar-inverse">
		<div class="navbar-header">
			<a class="navbar-brand" href="/">Mini-Twitter</a>
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse" aria-expanded="false">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
		</div>
		<div class="collapse navbar-collapse" id="navbar-collapse">
			<ul class="nav navbar-nav">
				<li><a href="//www.sswbelser.com" target="_blank">Made by SSWBelser</a></li>
				<li><a href="//github.com/sswbelser/sswbelser-twitter" target="_blank"><i class="fa fa-github-square"></i></a></li>
			</ul>
			<% if current_user %>
			<!-- renders if user is logged in -->
				<a class="btn navbar-btn navbar-right btn-danger" href="/logout" id="logout_button">Log out</a>
				<p class="navbar-text navbar-right">Welcome, <%= current_user.name %></p>
			<% else %>
			<!-- renders if user isn't logged in -->
				<a class="btn navbar-btn navbar-right btn-default" href="/auth/twitter" id="login_button">Log in to Twitter</a>
			<% end %>
		</div>
	</nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

	<title>SSWBelser Twitter</title>

	<!-- Bootstrap CSS -->
	<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">

	<!-- Bootstrap Optional CSS -->
	<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">

	<!-- Font Awesome -->
	<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">

	<%= stylesheet_link_tag 'application', media: 'all' %>

	<%= csrf_meta_tags %>
	
</head>
<body>

	<%= render "layouts/navbar" %>

	<div class="container text-center">
		<% flash.each do |name, msg| %>
			<%= content_tag :div, msg, class: "alert #{name == 'error' ? 'alert-danger' : 'alert-info'}" %>
		<% end %>
	</div>

	<div class="container">
		<%= yield %>
	</div>

	<!-- jQuery -->
	<script src="//code.jquery.com/jquery-1.11.3.min.js"></script>

	<!-- Bootstrap JS -->
	<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

	<%= javascript_include_tag 'application' %>

</body>
</html>

app/views/site/index.html.erb
<!-- refreshes feed every minute -->
<body onload="JavaScript:refreshTimer(60000);">
<div class="text-center">
    <h1>Timeline</h1>
</div>
<% if current_user %>
<!-- renders if user is logged in -->
	<div class="col-md-6">
		<div class="text-center">
			<h2>Highlighted Tweets</h2>
		</div>
		<br><br><br><br>
		<% current_user.home_timeline.each do |t| %>
		<!-- renders 20 most recent from user's timeline -->
			<div class="panel panel-success">
				<div class="panel-heading">
					<!-- tweeter's picture and username -->
					<img src="<%= t.user.profile_image_url_https %>"><span>
					<a href="<%= t.user.url %>"><%= t.user.screen_name %></a></span>
				</div>
				<div class="panel-body">
					<!-- tweet text -->
					<p><%= t.text %></p>
					<p>Retweets: <%= t.retweet_count %></p>
				</div>
				<div class="panel-footer">
					<p>Tweeted at: <%= t.created_at %></p>
				</div>
			</div>
		<% end %>
	</div>
	<div class="col-md-6">
		<div class="text-center">
			<h2>My Tweets</h2>
		</div>
		<br>
		<!-- new tweet button -->
		<%= link_to 'New Tweet', new_tweet_path, class: "btn btn-primary btn-block" %>
		<br>
		<% current_user.user_timeline.each do |t| %>
		<!-- renders 20 most recent user's tweets -->
			<div class="panel panel-warning">
				<div class="panel-heading">
					<!-- user's picture and username -->
					<img src="<%= t.user.profile_image_url_https %>"><span>
					<a href="<%= t.user.url %>"><%= t.user.screen_name %></a></span>
				</div>
				<div class="panel-body">
					<!-- tweet text -->
					<p><%= t.text %></p>
					<p>Retweets: <%= t.retweet_count %></p>
				</div>
				<div class="panel-footer">
					<p>Tweeted at: <%= t.created_at %></p>
				</div>
			</div>
		<% end %>
	</div>
<% else %>
<!-- renders if user isn't logged in -->
	<div class="text-center">
		<h4>Please <%= link_to "log in to Twitter", "/auth/twitter" %> to view your feed</h4>
	</div>
<% end %>
</body>

app/views/tweets/_form.html.erb
<!-- new tweet form -->
<div class="col-md-4 col-md-offset-4">
	<%= form_for :tweet, url: tweets_path, method: :post, html: { id: "new_tweet" } do |f| %>
		<div class="form-group">
			<%= f.text_area :message, placeholder: "Enter post", autofocus: true, class: "form-control" %>
		</div>
		<hr>
		<%= f.submit "Tweet!", class: "btn btn-primary btn-block" %>
	<% end %>
</div>

app/views/tweets/new.html.erb
<!-- view with the tweet creation form -->
<div class="text-center">
	<h1>New Tweet</h1>
</div>
<br><br>
<!-- partial in case CRUD is added -->
<%= render 'form' %>